### ISSUE TITLE
Update imports on file rename is not working

### ISSUE THREAD

**Issue by Demianeen** [yioneko/vtsls#119]
I did setup vtsls with neovim and was excited to move from tsserver to LSP close to vscode one. After setup I have a new issue: imports are not updated on file rename. But in LSP capabilities I mentioned the fileOperation capability:
```
fileOperations: {
        didRename: {
          filters: [
            {
              scheme: "file",
              pattern: {
                glob: "**/*.{ts,cts,mts,tsx,js,cjs,mjs,jsx}",
                matches: "file",
              },
            },
            {
              scheme: "file",
              pattern: {
                glob: "**/*",
                matches: "folder",
              },
            },
          ],
        },
      },
 ```
 I use nvim cmp alongside Mason and Mason LSP config. Is this the issue with nvim or vtsls?

**Comment by yioneko** [comment]
Neovim doesn't support `workspace/didRenameFiles` notification so additional handling should be done on the client side to make this work. Assuming that you are using a file manager plugin, take a look at [my implementation for automatic paths update](https://github.com/yioneko/nvim-vtsls#other-useful-snippets) for reference. It just requires sending the notification including files paths to the server, and most of the file manager plugins expose APIs to subscribe the renaming event. If you are using `nvim-tree.lua`, then directly copy and paste the snippet will just work.

**Comment by Demianeen** [comment]
I didn't know such scripts exist! 

Where did you add it though? I am using lazy.nvim and added it to nvim-tree config option only to get:
```
Failed to run 'config' for nvim-tree.Lua

...l/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/events.lua:31: table index is nil
```

**Comment by yioneko** [comment]
Sorry for my mistake, there is a small typo in the original snippet (haven't found it untill your feedback 😅):
```lua
api.events.subscribe(api.events.Event.NodeRename
```
```lua
api.events.subscribe(api.events.Event.NodeRenamed
```

**Comment by Demianeen** [comment]
Wow, amazing man! Thank you)
