### ISSUE TITLE
vtsls and typescript-language-server don't retrieve all references when trying to retrieve code references

### ISSUE THREAD

**Issue by andy-wong-andy-wong** [yioneko/vtsls#132]
I'm not sure if this is a vtsls/typescript-language-server issue, or a LSP4J issue, but it seems like there are some references that don't get captured when I try to access the code references via `LanguageServer.textDocumentService.references`.

However, this only retrieves the first reference of the variable. There are other instances of the references that are not retrieved. The particular issue is in a React Typescript file. The file contains the following:

```
val variableName = true

... many lines down...

{ variableName &&
...
```

LSP4J only seems to capture the first reference, and does not grab the second instance.

**Comment by yioneko** [comment]
You can try it in VSCode. If the same problem could be reproduced there, then I suspect that this is the issue of tsserver, and should be reported to [TypeScript](https://github.com/microsoft/typescript).

**Comment by yioneko** [comment]
Closed due to inactivity. Feel free to reopen one if more information could be provided, like a reproducible example.

**Comment by NextMerge** [comment]
For a moment I thought I had encountered this issue as well. I eventually figured out that when looking at references it won't show the reference you're currently on, so it always shows the total number minus one.

Just an fyi incase anyone else stumbles upon this issue.
