### ISSUE TITLE
How to add a global fix to 'remove all unused imports' to code action?

### ISSUE THREAD

**Issue by chaozwn** [yioneko/vtsls#150]
How to add a global fix to 'remove all unused imports' to code actions, like `typescript-tools.nvim`.

![image](https://github.com/yioneko/vtsls/assets/51357674/558b2663-ba58-4f1c-b055-7bbc9dd568f5)

**Comment by yioneko** [comment]
`:lua vim.lsp.buf.code_action({ context = { only = { "source" } } })`

Or use `:lua vim.lsp.buf.code_action({ context = { only = { "source", "refactor", "quickfix" } } })` to see all of the available code actions.

**Comment by chaozwn** [comment]
> `:lua vim.lsp.buf.code_action({ context = { only = { "source" } } })`
> 
> Or use `:lua vim.lsp.buf.code_action({ context = { only = { "source", "refactor", "quickfix" } } })` to see all of the available code actions.

Thank you for your response, but I hope that these options are available by default in the buffer using code action, just like `Move to a new File`.
