### ISSUE TITLE
TSServer gets more correct import suggestion than vtsls

### ISSUE THREAD

**Issue by sinelnikov-web** [yioneko/vtsls#151]
On the screenshot the first option is from vtsls and it's import incorrect.
It will be ok if it would suggest me several variants, but vtsls give only one and incorrect.

But below you can see the sixth option, it comes from tsserver and it's absolutely right.

How I can get the same result with vtsls?

![telegram-cloud-photo-size-2-5213062907263310788-y](https://github.com/yioneko/vtsls/assets/67955139/5f53415e-d022-4154-804e-8dd9e428da00)

**Comment by yioneko** [comment]
Could you try it in VSCode? The server does not touch any code about code action of missing import, and if it behaves differently I would look into the problem.

**Comment by yioneko** [comment]
Then the issue should be reported to VSCode repo. Once it is fixed there, we just need to update the referenced VSCode submodule.
