### ISSUE TITLE
Not working with yarn plug and play

### ISSUE THREAD

**Issue by utrumo** [yioneko/vtsls#169]
The problem is that in the working project we use yarn plug and play, and this plugin does not work with it - it does not find type declarations for third-party modules.

`Cannot find module 'fp-ts' or its corresponding type declarations. [2307]`

If I add to `.yarnrc.yml`:
`nodeLinker: node-modules`

and run `yarn install`
packages are installed in the node_module and this plugin will start working.

Moreover, there is no problem in vscode.
What can be tweaked in the settings so that vtsls works with yarn plug and play?

**Comment by yioneko** [comment]
Ensure the yarn ts sdk path `./.yarn/sdks/typescript/lib` exists (ref https://yarnpkg.com/getting-started/editor-sdks) and set config option `typescript.tsdk = "./.yarn/sdks/typescript/lib"` and `vtsls.autoUseWorkspaceTsdk = true`.

**Comment by utrumo** [comment]
@yioneko, thank you! It helped!

For LazyVim users:
you just need to add the lua/plugins/typescript.lua file with the following content:
```lua
return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      vtsls = {
        settings = {
          typescript = {
            tsdk = "./.yarn/sdks/typescript/lib",
          },
        },
      },
    },
  },
}

```

**Comment by rose-m** [comment]
Can this be achieved without explicitly settings `typescript.tsdk` to a certain path? I've set the `autoUseWorkspaceTsdk` option but it does not pick up the yarn workspace typescript SDK.

**Comment by yioneko** [comment]
> I'd hope for the auto setting to make it look for that SDK folder automatically.

I'm not a fan of this as [it is the vscode typescript extension that only searches local tsdk in `node_modules/typescript/lib`](https://github.com/microsoft/vscode/blob/83b92b5e974ed5b67559d6176848f2b11b5f24de/extensions/typescript-language-features/src/tsServer/versionProvider.electron.ts#L125-L128), and I'd prefer not to change this behavior. Is there any other rationale for this feature?

**Comment by rose-m** [comment]
That is interesting - thanks for the link. I see your point, it would be some indirect magic that is brittle. I was somewhat confused because I thought that VSCode would magically look it up, but the `yarn dlx` command is the one that generates the appropriate settings.

I'm coming from neovim and thus project-specific settings are sometimes just a pain to set up but I agree that should be the way to go!

Sorry for taking your time 😊

**Comment by rose-m** [comment]
This has suddenly stopped working for me. It's back to not being able to find packages and if I restart the tsserver with logging it shows me this:
```
Info 0    [18:20:29.684] Starting TS Server
Info 1    [18:20:29.685] Version: 5.5.2
Info 2    [18:20:29.685] Arguments: .../.nvm/versions/node/v20.13.1/bin/node .../.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/8z/63m_s1lx287gfggmhth9ql680000gn/T/vscode-typescript501/6de0648efea846c5536c/tscancellation-1aa0a45658830c6f39a5.tmp* --logVerbosity verbose --logFile /var/folders/8z/63m_s1lx287gfggmhth9ql680000gn/T/tsserver-log-4F0Oap/tsserver.log --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
```

**Comment by leokang94** [comment]
I recently switched to using the native lsp in nvim v0.11.2, and found a way to dynamically respond to yarn pnp without having to have a separate `.nvim.lua` file for each plugin or each repository.

The idea is that the lsp settings will only make basic settings, and the `before_init` will merge the typescript-specific options from the repository `.vscode/settings.json` with the existing settings.

As you may be familiar with if you use yarn pnp, you can't get the tsserver of the typescript server from node_modules, so you need to tell vscode where the tsserver is located via `yarn dlx @yarnpkg/sdks vscode`.

> Actually, `yarn dlx @yarnpkg/sdks vim` is fine, it just needs to be relative to .vim/coc-settings.json, not .vscode/settings.json.

First, create a `get_vscode_typescript_settings(root_dir)` function to get the typescript settings in .vscode/settings.json from `root_dir` in config (thanks, claude !)

```lua
-- Function to read VSCode settings and extract TypeScript configurations
local function get_vscode_typescript_settings(root_dir)
	local vscode_settings_path = root_dir .. "/.vscode/settings.json"

	-- Check if .vscode/settings.json exists
	if vim.fn.filereadable(vscode_settings_path) == 0 then
		return {}
	end

	-- Read and parse the JSON file
	local ok, content = pcall(vim.fn.readfile, vscode_settings_path)
	if not ok then
		return {}
	end

	local json_str = table.concat(content, "\n")
	local ok_decode, vscode_settings = pcall(vim.json.decode, json_str)
	if not ok_decode then
		return {}
	end

	-- Extract TypeScript related settings
	local typescript_settings = {}
	for key, value in pairs(vscode_settings) do
		if key:match("^typescript%.") then
			-- Convert "typescript.preferences.something" to nested table structure
			local parts = vim.split(key, "%.")
			if #parts >= 2 then
				local current = typescript_settings
				for i = 2, #parts - 1 do
					if not current[parts[i]] then
						current[parts[i]] = {}
					end
					current = current[parts[i]]
				end
				current[parts[#parts]] = value
			end
		end
	end

	return typescript_settings
end
```

Then, add `before_init` to lsp.config as shown below.
```lua
---@type vim.lsp.Config
return {
	before_init = function(_, config)
		-- Read VSCode settings when a new config is created
		local vscode_ts_settings = get_vscode_typescript_settings(config.root_dir)

		-- Merge VSCode TypeScript settings with default settings
		if next(vscode_ts_settings) then
			config.settings.typescript = vim.tbl_deep_extend("keep", settings, vscode_ts_settings)
		end
	end,
}
```

For reference, I'm using `root_dir` as shown below to handle the monorepo case.
```lua
-- core/lsp/utils.lua
local M = {}

M.get_monorepo_root = function(startpath)
	return vim.fs.dirname(
		vim.fs.find(
			{ ".git", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb" },
			{ path = startpath, upward = true }
		)[1]
	)
end

---@type fun(bufnr: number, on_dir: fun(dir: string))
M.get_root_dir = function(bufnr, on_dir)
	local full_path = vim.api.nvim_buf_get_name(bufnr)
	local root_path = M.get_monorepo_root(full_path)

	if root_path and vim.fn.isdirectory(root_path) == 1 then
		on_dir(root_path)
	else
		on_dir(vim.fs.dirname(full_path))
	end
end

return M

-- lsp/vtsls.lua
local LspUtils = require("core.lsp.utils")

return {
  root_dir = LspUtils.get_root_dir
}
```

Maybe it only works well in my environment, but I thought I'd share it in case it might help someone else.

**Comment by heywhy** [comment]
One way I got it working using the native neovim `vim.lsp.config` is below;

```lua
vim.lsp.config('vtsls', {
  init_options = {
    hostInfo = 'neovim'
  },
  settings = { ... }
})
```

Setting the hostinfo to neovim is very important, and having `lbrayner/vim-rzip` (n)vim extension is also important. Then in your project, you can set the `typescript.tsdk = "./.yarn/sdks/typescript/lib"` setting for the vtsls.

**Comment by heywhy** [comment]
The above is redundant since this [nvim-lspconfig PR](https://github.com/neovim/nvim-lspconfig/pull/4048) got merged.
