### ISSUE TITLE
Feature request: Truncation limit for inlay hints

### ISSUE THREAD

**Issue by MariaSolOs** [yioneko/vtsls#170]
TypeScript is known for its verbose inlay hints, and it would be nice to offer a truncation setting that could be applied here:
https://github.com/yioneko/vtsls/blob/f26fd360b9979357112f049bc7b2cf39ee814952/packages/service/src/utils/converter.ts#L588-L596

I know that customizations like these might be a hassle to maintain, and I actually had [a workaround in my config](https://github.com/MariaSolOs/dotfiles/blob/bb86c4e95925f6b20a3b2135b49da870b631642c/.config/nvim/lua/lsp.lua#L262). However since this plugin deals with concatenating interactive inlay hints, overriding the handler doesn't really work anymore...

**Comment by yioneko** [comment]
It's fine to have this feature, especially since TypeScript is likely the language most often facing this issue. But I'm unsure whether this feature should be implemented on the server side or the client side. I see [VSCode truncate the hint one client side and do that on a line basis](https://github.com/microsoft/vscode/commit/401d89f2cb622496857f13741f5535e4be4589be), and if we truncate on server side, we could only truncate by hint, which is less flexible.

I looked at your workaround and I think it could also be adapted for this server after minor modifications? I've tested the following snippet and I'm not sure if this could solve your problem:
```lua
local inlay_hint_method = vim.lsp.protocol.Methods.textDocument_inlayHint
local inlay_hint_handler = vim.lsp.handlers[inlay_hint_method]
local ellipsis = "…"
vim.lsp.handlers[inlay_hint_method] = function(err, result, ctx, config)
  local client = vim.lsp.get_client_by_id(ctx.client_id)
  if client and (client.name == "typescript-tools" or client.name == "vtsls") then
    result = vim
      .iter(result)
      :map(function(hint)
        local label_remaining = 30
        local label = hint.label
        if type(label) == "string" and label:len() >= label_remaining then
          local truncated = label:sub(1, label_remaining - 1) .. ellipsis
          hint.label = truncated
        elseif type(label) == "table" then
          local truncated = {}
          for _, part in ipairs(label) do
            if part.value:len() < label_remaining then
              table.insert(truncated, part)
              label_remaining = label_remaining - part.value:len()
            else
              part.value = part.value:sub(1, label_remaining - 1) .. ellipsis
              table.insert(truncated, part)
              break
            end
          end
          hint.label = truncated
        end
        return hint
      end)
      :totable()
  end
  inlay_hint_handler(err, result, ctx, config)
end
```

**Comment by MariaSolOs** [comment]
> But I'm unsure whether this feature should be implemented on the server side or the client side.

I agree with you. In fact I've participated in related discussions about this in Neovim (https://github.com/neovim/neovim/issues/27240 and https://github.com/neovim/neovim/pull/27241). However when I think about this issue I can see arguments of why this should be done by the server, while I also find the client truncation better extensible. It's complicated hehe.

And yeah I guess that I can continue using my workaround, but then I need to copy the logic you have here to concatenate `InlayHintLabelPart`s, and so I find it cleaner to do all of the processing in one place (preferably in this plugin). In fact, it would be nice to offer a callback formatter instead of just a truncation limit for better flexibility.

I again understand if this is too much trouble though.

**Comment by MariaSolOs** [comment]
@yioneko Since #173 got merged (and thank you for that!) I'll close this now :)
