### ISSUE TITLE
Unneeded popup when using custom node version

### ISSUE THREAD

**Issue by kuba-gaj** [yioneko/vtsls#174]
I started using custom node version with pointer expression enabled as vtsls was crushing with OOM in our monorepo, as described here: https://github.com/yioneko/vtsls/issues/136

It worked but now when the servers starts I see this popup:
![image](https://github.com/yioneko/vtsls/assets/3915056/7daa6127-fb69-4b0a-b904-a8ec105c3464)

It looks like it's not blocking and vtsls initializes anyway and I don't think it matters what I select. Is it possible to not display it?

**Comment by yioneko** [comment]
You'll see the prompt if you set the custom node path by option `typescript.tsserver.nodePath`, and to suppress the prompt needs another patch to the vscode extension. 

For now, if you are using nvim, you can set the node path by overriding the `cmd` of vtsls to `/path/to/node /path/to/vtsls_bin --stdio`, and the prompt will disappear if `typescript.tsserver.nodePath` is unset.

**Comment by kuba-gaj** [comment]
That worked, thank you
