### ISSUE TITLE
Running vtsls--stdio

### ISSUE THREAD

**Issue by jakejjoyner** [yioneko/vtsls#181]
When I run this command, it just gets stuck and doesn't do anything.

**Comment by yioneko** [comment]
It is blocked on stdin and will output the response in stdout if received request in proper format. To communicate with language server, refer to [LSP doc](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseProtocol) for message format. Or if you want to use it programmatically, here is a [standalone service package](https://github.com/yioneko/vtsls/tree/main/packages/service) which could better serve your need.

**Comment by yioneko** [comment]
Any further questions? If not, I'll close it for now.
