### ISSUE TITLE
Crashes in monorepo

### ISSUE THREAD

**Issue by iamim** [yioneko/vtsls#183]
When I open a root folder containing 2 TS projects (`ProjectA` and `ProjectB`) and open one of them vtsls initializes properly. However, when I try to open a buffer from its sibling project (`ProjectB`), vtsls is stuck re-initializing and failing.

I can see in `:LspInfo` ran from `ProjectA/index.ts` that it initializes correctly with the root set to `/ProjectA`. `:LspInfo` from the problematic `ProjectB` shows either that it's running in a single file mode or set to `/ProjectA`.

This is my config in `nvim-lspconfig`:
```
vtsls = {
  filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
  settings = {
    vtsls = {
      -- autoUseWorkspaceTsdk = true,
      tsserver = {
        globalPlugins = {
          {
            name = '@vue/typescript-plugin',
            location = '/opt/homebrew/lib/node_modules/@vue/typescript-plugin',
            languages = { 'vue' },
            configNamespace = 'typescript',
            enableForWorkspaceTypeScriptVersions = true,
          },
        },
      },
    },
  },
},
```

**Comment by yioneko** [comment]
Root directory is determined on the client side, you should check the `root_dir` function of lspconfig. Does the server still crash if you disable all the ts plugins?

**Comment by iamim** [comment]
Thanks for replying!
`root_dir` should be fine as it's the one set in `nvim-lspconfig`.

I believe I found the issue. It seems like the node process managing tsserver runs out of memory. The two projects I'm working with are fairly small but they import a lot of type definitions. Is there a way to spawn a new node instance per project or increase `--max-old-space-size` of the node instance (you can see that it's set to 3GiB)?

What happens is that as I open a second project, the memory of the node process on the picture goes to 3.2GiB and it crashes shortly.

<img width="825" alt="image" src="https://github.com/yioneko/vtsls/assets/14250177/5e4a8844-18a6-478c-bd00-e2ee84987070">

**Comment by yioneko** [comment]
Good catch. The memory limit is controlled by [`typescript.tsserver.maxTsServerMemory`](https://github.com/yioneko/vtsls/blob/6adfb5d3889ad4b82c5e238446b27ae3ee1e3767/packages/service/configuration.schema.json#L906-L910) and it defaults to 3GB which is the same as VSCode default. You can increase that limit to see if it solves your problem. I'll consider removing that limit by default since I've seen many people reporting the server crashed on large monorepo.

**Comment by yioneko** [comment]
Added a section in README for it: https://github.com/yioneko/vtsls/commit/376a43d19359dfaf0af0bbd1ddfba0abdcaa354e

**Comment by iamim** [comment]
Awesome, thanks!

I wonder how vscode handled those 2 projects with no issues.

**Comment by yioneko** [comment]
VSCode uses a special built Node.js to reduce the memory usage by nearly half: https://github.com/yioneko/vtsls/issues/136#issuecomment-1919246219

**Comment by iamim** [comment]
Crazy, didn't know that. Thank you for your assistance!

**Comment by iamim** [comment]
Since vscode uses a custom runtime to run `tsserver`, could it be a good experimental feature for this LSP? Maybe `bun`, or other runtimes?

**Comment by yioneko** [comment]
I think the server as a npm package could not control the runtime used to run it, users are free to choose any runtime through cmd like `/path/to/runtime /path/to/vtsls_bin --stdio`. There is also [a setting `typescript.tsserver.nodePath`](https://github.com/yioneko/vtsls/blob/376a43d19359dfaf0af0bbd1ddfba0abdcaa354e/packages/service/configuration.schema.json#L1021C33-L1024) to specifically control the runtime used for `tsserver`. However, at least we could document which runtime is supported like the special node compiled with pointer compression.
