### ISSUE TITLE
Ignore Certain Diagnostic Codes like tsserver

### ISSUE THREAD

**Issue by bnwa** [yioneko/vtsls#187]
Neovim user comparing the configuration properties between [tsserver](https://github.com/typescript-language-server/typescript-language-server/blob/master/docs/configuration.md) and [vtsls](https://github.com/yioneko/vtsls/blob/main/packages/service/configuration.schema.json) and I notice that the following config properties don't exist in vtsls:
```lua
{
  diagnostics = {
    ignoredCodes = {
      -- 80001, -- "File can be converted to ES module"
    },
  },
}
```
Am I missing something? Does vtsls implicitly accept certain tsserver properties or is this just not configurable at present?

**Comment by yioneko** [comment]
The configuration properties are mostly inherited from VSCode typescript extension and `ignoreCodes` is not implemented upstream. This is a `typescript-language-server` own implementation so you won't see that here.

You can do that in nvim by overriding the handler:
```lua
local ignored_codes = { [8001] = true }
local handler = vim.lsp.handlers[vim.lsp.protocol.Methods.textDocument_publishDiagnostics]
vim.lsp.handlers[vim.lsp.protocol.Methods.textDocument_publishDiagnostics] = function(...)
  local res = select(2, ...)
  if res then
    local filtered = vim
      .iter(res.diagnostics or {})
      :filter(function(d)
        return d.source == "ts" and ignored_codes[d.code] == nil
      end)
      :totable()
    res.diagnostics = filtered
  end
  return handler(...)
end
```

I think the feature could be better implemented on the client side since user may want to filter codes for various servers. But I won't be against adding this to server side as a temporary solution since some clients may be lack of that capability.

**Comment by bnwa** [comment]
Ah, understood, thanks for the pointer

**Comment by victor-falcon** [comment]
I did this and it's working fine:

```
	{
		"neovim/nvim-lspconfig",
		opts = {
			-- Override the diagnostics handler to ignore TS error code 2786
			setup = {
				vtsls = function(_, _)
					local ignored_ts_codes = { [2786] = true }

					local original_handler = vim.lsp.handlers[vim.lsp.protocol.Methods.textDocument_publishDiagnostics]

					vim.lsp.handlers[vim.lsp.protocol.Methods.textDocument_publishDiagnostics] = function(
						err,
						result,
						ctx,
						config
					)
						if result then
							local filtered = vim.tbl_filter(function(d)
								return d.source ~= "ts" or not ignored_ts_codes[d.code]
							end, result.diagnostics)
							result.diagnostics = filtered
						end
						return original_handler(err, result, ctx, config)
					end
				end,
			},
		},
	}
```

PS: I know this is old, it's just for helping others because this is well indexed on Google.
