### ISSUE TITLE
[Question]: Purpose of this project

### ISSUE THREAD

**Issue by HugeLetters** [yioneko/vtsls#194]
Sorry for a silly issue but I've just randomly stumbled upon this project and I would like to understand what does it do?

What would be potential benefit for using vtsls over regular vscode extension? Or is the purpose is that it allows to use vscode like features in other editors like nvim?

**Comment by yioneko** [comment]
> Or is the purpose is that it allows to use vscode like features in other editors like nvim?

Exactly. The server does not target on VSCode.
