### ISSUE TITLE
Where to increase maxTsServerMemory?

### ISSUE THREAD

**Issue by typicode** [yioneko/vtsls#195]
Hi,

I have some trouble finding where `typescript.tsserver.maxTsServerMemory` should be set?
For context, I'm using LazyVim.

**Comment by yioneko** [comment]
```lua
return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      vtsls = {
        settings = {
          typescript = {
            tsserver = {
              maxTsServerMemory = ...
            },
          },
        },
      },
    },
  },
}
```

**Comment by typicode** [comment]
Thanks a lot!
So I've created a file `lua/plugins/lsp.lua` with the content above and it works!

**Comment by typicode** [comment]
Maybe it could be interesting to add it to the docs?
