### ISSUE TITLE
Is there a way to stop completion results from including file text?

### ISSUE THREAD

**Issue by jonathan-elize** [yioneko/vtsls#198]
Hi, so I was using this lsp and noticed that it seems to be returning text from the file that is open during autocompletion. I would like to avoid this as it leads to excess completion items. Is there a setting that can be used to turn this off? I didn't seem to find one in the server configurations that would apply to this: https://github.com/yioneko/vtsls/blob/main/packages/service/configuration.schema.json . But wanted to ask to check.

For examples, here are screenshots of completion items from vtsls vs tsserver:

Vtsls:
<img width="610" alt="Screenshot 2024-08-26 at 8 45 22 PM" src="https://github.com/user-attachments/assets/8efd50b8-539c-4ef1-8dab-9a0cfe2110de">

Tsserver:
<img width="438" alt="Screenshot 2024-08-26 at 8 46 22 PM" src="https://github.com/user-attachments/assets/541026e4-48b1-4057-988d-89d34717cdd4">

Edit: I've been inspecting the response from the lsp and it seems like the extra items in vtsls are actually coming through without a `kind` field being set in case that helps

**Comment by yioneko** [comment]
[`javascript.suggest.names`](https://github.com/yioneko/vtsls/blob/bbe6d6f3b50a3ae9d929a65bbb5e9db07e25ce49/packages/service/configuration.schema.json#L553-L5570)

**Comment by jonathan-elize** [comment]
Thank you @yioneko ! This worked to solve the issue.

Just for anyone that might come later. This is what I did to apply this. I had to update the settings sent over to the lsp to set the value to false. I use neovim for example and this is what I did to update the settings accordingly:

```lua
  settings = {
   --... other settings
    javascript = {
      suggest = {
        names = false,
      },
    },
  },

```
