### ISSUE TITLE
Executing `typescript.openTsServerLog` triggers an error

### ISSUE THREAD

**Issue by rchl** [yioneko/vtsls#27]
Opening log file with `typescript.openTsServerLog` crashes in

https://github.com/yioneko/vtsls/blob/8578f8e5386ec28d764c8ddcb07c5953d911adb8/packages/service/src/utils/converter.ts#L150-L150

because this fake text document that is created in:

https://github.com/yioneko/vtsls/blob/e9dcd93dab99f9f5e6ede3a97b8ecacfdf42bf82/packages/service/src/shims/workspace.ts#L237-L242

is missing some properties. Using `satisfies TextDocument` instead of `as TextDocument` will show which properties are missing.

The text document is missing because this file type is not handled by the server.

Here is LSP log when trigger this command:

```
:: --> LSP-vtsls workspace/executeCommand(5): {'command': 'typescript.openTsServerLog', 'workDoneToken': '$ublime-5'}
:: <-  LSP-vtsls $/progress: {'token': '4da26fb5-3aba-4216-9d63-7b05d2ce48a2', 'value': {'kind': 'end'}}
:: <-- LSP-vtsls window/showDocument(4): {'uri': 'file:///var/folders/b0/93shkzpj2q39wrc0hhc22jbr0000gn/T/tsserver-log-KirIVq/tsserver.log', 'external': False}
:: <<< LSP-vtsls 5: None
:: >>> LSP-vtsls 4: {'success': True}
:: <-  LSP-vtsls textDocument/publishDiagnostics: {'uri': 'file:///usr/local/workspace/github/vtsls/packages/service/tsconfig.json', 'diagnostics': []}
:: <-  LSP-vtsls textDocument/publishDiagnostics: {'uri': 'file:///usr/local/workspace/github/vtsls/packages/service/src/typescript-language-features/src/typescriptServiceClient.ts', 'diagnostics': [{'tags': [1], 'severity': 4, 'range': {'start': {'line': 516, 'character': 9}, 'end': {'line': 516, 'character': 10}}, 'source': 'ts', 'code': 6133, 'message': "'r' is declared but its value is never read."}]}
LSP-vtsls: Command revealFileInOS not found
```

**Comment by yioneko** [comment]
Thanks for catching this. I learned that mainstream lsp client just uses filetype to determine the attached server, while we cannot use selector like `^tsconfig.json` to register some concrete files, although documented in lsp spec.
