### ISSUE TITLE
formatting alwayse choose 4space style indentation

### ISSUE THREAD

**Issue by hrsh7th** [yioneko/vtsls#28]
### Problem

The neovim's LSP client sends [FormattingOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions) to the server.
But `vtsls` server ignores this options.

### Configuration

```
  require'lspconfig'.vtsls.setup {
    settings = {
      javascript = {
        suggest = {
          completeFunctionCalls = true,
        }
      },
      typescript = {
        suggest = {
          completeFunctionCalls = true,
        },
        preferences = {
          importModuleSpecifier = 'relative',
        }
      },
    }
  }
```

**Comment by yioneko** [comment]
Fixed in https://github.com/yioneko/vtsls/commit/8631f47cf2645e5a56dc7d6d928542c2006d32db. I'll publish a new release (0.1.9) soon.

**Comment by hrsh7th** [comment]
This is what everyone has been waiting for. Gratitude
